### ISSUE TITLE
Release of requests 2.9.1

### ISSUE THREAD

**Issue by nazroll** [agfor/braintree-python-appengine#2]
Does the braintree library still produce the same errors on App Engine, with the new requests 2.9.1?

**Comment by agfor** [comment]
Unfortunately, `requests` doesn't consider GAE a supported platform, so this is unlikely to be fixed in `requests` directly. However, in 2.10.0, it should be possible to use `requests_toolbelt` instead of the fixes references here. See [the `requests-toolbelt` adapter docs](https://github.com/sigmavirus24/requests-toolbelt/blob/master/docs/adapters.rst#appengineadapter) for more information.

I've added that info to the README.
